name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Inject API key into HTML
        run: |
          # Check if API key secret exists
          if [ -z "${{ secrets.OPENROUTER_API_KEY }}" ]; then
            echo "❌ Error: OPENROUTER_API_KEY secret not found!"
            echo "Please add OPENROUTER_API_KEY to repository secrets:"
            echo "Repository → Settings → Secrets and variables → Actions → New repository secret"
            exit 1
          fi
          
          echo "🔍 Before injection:"
          grep -n "{{OPENROUTER_API_KEY}}" index.html || echo "Placeholder not found"
          
          # Use sed to replace the placeholder directly
          sed -i 's/{{OPENROUTER_API_KEY}}/${{ secrets.OPENROUTER_API_KEY }}/g' index.html
          
          echo "✅ After injection:"
          # Check if placeholder still exists (should not)
          if grep -q "{{OPENROUTER_API_KEY}}" index.html; then
            echo "❌ Error: Placeholder still exists!"
            exit 1
          else
            echo "✅ API key successfully injected"
          fi
          
          # Verify API key pattern exists
          if grep -q "sk-or-v1-" index.html; then
            echo "✅ API key pattern found in file"
          else
            echo "⚠️ Warning: Expected API key pattern not found"
          fi
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4