name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # This workflow is now designed for a platform like Netlify or Vercel.
      # The hosting provider will handle the build and deployment.
      # The OPENROUTER_API_KEY secret should be set as an environment variable
      # in the hosting provider's settings, not in GitHub Actions.
      
      - name: Verify Files for Deployment
        run: |
          echo "✅ Verifying key files for serverless deployment:"
          ls -l
          echo "---"
          ls -l netlify/functions
          
          # The placeholder should no longer exist in index.html
          if grep -q "{{OPENROUTER_API_KEY}}" index.html; then
            echo "❌ Error: API key placeholder found in index.html. It should have been removed."
            exit 1
          else
            echo "✅ API key placeholder is correctly removed from index.html."
          fi
          
          echo "✅ Verification complete. Ready for deployment to a serverless platform."